### ISSUE TITLE
Fake the getUserMedia too

### ISSUE THREAD

**Issue by Sfinx** [eface2face/rtcninja-fake#2]
JsSIP is nearly useless without fake getUserMedia in nodejs. Help it a little bit

```
diff -urN rtcninja-fake.orig/index.js rtcninja-fake/index.js
--- rtcninja-fake.orig/index.js 2015-04-01 13:38:56.000000000 +0300
+++ rtcninja-fake/index.js      2016-11-02 22:26:22.250796345 +0200
@@ -10,6 +10,7 @@
  */
        RTCPeerConnection = require('./lib/RTCPeerConnection'),
        RTCSessionDescription = require('./lib/RTCSessionDescription'),
+       getUserMedia = require('./lib/getUserMedia'),
        RTCIceCandidate = require('./lib/RTCIceCandidate');
 
 
@@ -42,5 +43,6 @@
        RTCPeerConnection:      RTCPeerConnection,
        RTCSessionDescription:  RTCSessionDescription,
        RTCIceCandidate:        RTCIceCandidate,
+       getUserMedia:           getUserMedia,
        canRenegotiate:         true
 };
diff -urN rtcninja-fake.orig/lib/getUserMedia.js rtcninja-fake/lib/getUserMedia.js
--- rtcninja-fake.orig/lib/getUserMedia.js      1970-01-01 03:00:00.000000000 +0300
+++ rtcninja-fake/lib/getUserMedia.js   2016-11-02 22:29:36.378713481 +0200
@@ -0,0 +1,6 @@
+/**
+ * Expose the getUserMedia class.
+ */
+module.exports = getUserMedia;
+
+function getUserMedia(c, s, e) { s(); }
```

**Comment by ibc** [comment]
I don't fully understand. Why do you need a fake `getUserMedia()` function if it returns nothing and does not provide you with a (even fake) `MediaStream` object?

**Comment by Sfinx** [comment]
I do not need it at all. The rtcninja has internal check 'if (getUserMedia)' and fails with exception 'WebRTC not supported' when using JsSIP in node. So this means that JsSIP need this patch to be able to make single call ever under nodejs.

**Comment by ibc** [comment]
The fact is that [next version of JsSIP](https://github.com/versatica/JsSIP/tree/no-rtcninja) will no longer depend on `rtcninja`. May you use the `no-rtcninja` branch of JsSIP for now until it becomes `master`?

**Comment by Sfinx** [comment]
My main intention is to make JsSIP working under nodejs. Does the new JsSIP version allow to make calls under nodejs ? The current version just throws exception from rtpninja internals which makes all SIP stack unusable.

**Comment by ibc** [comment]
> Does the new JsSIP version allow to make calls under nodejs?

No. Node does not implement WebRTC. Maybe you can have the WebRTC API in Node by using Electron or something like that, but that's not something that depends on JsSIP.

**Comment by Sfinx** [comment]
I do not need Electron or WebRTC in node - I'd like to make calls from console apps. Is it make sense for you ? You have the chance to open the JsSIP to nodejs world just by slightly modifying the code. Seems like you author of JsSIP and you claimed that your software is running under nodejs. You have to be fair and remove the nodejs word from docs as 'running' - is just exception about missing WebRTC support upon start.

**Comment by ibc** [comment]
Please, keep calm.

> I'd like to make calls from console apps

Define "calls". Do you want to make audio/video calls from console apps? Please, confirm that.

**Comment by Sfinx** [comment]
"audio/video" - is the only SDP text definitions. I'm developing Kurento to Asterisk gateway using simple nodejs app, so just calling callJsSIP.ua.call() with call.on('sdp') callbacks. Trust me - there many such applications where people just need to process SIP messages without any media present at the processing point.

**Comment by ibc** [comment]
I perfectly understand that JsSIP should be media agnostic rather than handling the WebRTC API internally. However, that's not true at this moment. So, please confirm:
- Does adding the fake `getUserMedia()` in `rtcninja-fake` work for your use case? Please confirm yes or not.

**Comment by Sfinx** [comment]
Sure. I've finished the proxy and will post it here at github today (https://github.com/Sfinx/k2s) - it is perfectly running from console without any problems. The only problem is that it requires the jssip and rtcninja-fake patches to run.

**Comment by ibc** [comment]
Which jssip patch do you mean?

**Comment by Sfinx** [comment]
I've posted it to the closed by your yesterday issue. The success log of the JsSIP/Asterisk/Kurento connection:

```
rus@Yasha:~/kurento$ node  outgoing.js --call 110
  rtcninja version 0.7.0 +0ms
  rtcninja detected browser:   [mobile:false, tablet:false, android:false, ios:false] +4ms
  rtcninja WebRTC supported +55ms
  rtcninja WebRTC supported +5ms
  rtcninja WebRTC supported +1ms
connecting
connected
registered
incall pipeline created
initiated call
  rtcninja:RTCPeerConnection new | [pcConfig:{ iceServers: [] }, pcConstraints:null] +293ms
  rtcninja:RTCPeerConnection setConfigurationAndOptions | processed pcConfig: { iceServers: [] } +22ms
  rtcninja:FakePlugin:RTCPeerConnection new() +1ms
new outgoing call
Call to: <sip:110@10.1.1.208>
  rtcninja:Adapter getUserMedia() | constraints: { audio: true, video: false } +1ms
  rtcninja:Adapter getUserMedia() | success +1ms
  rtcninja:RTCPeerConnection createOffer() +1ms
  rtcninja:FakePlugin:RTCPeerConnection createOffer() +0ms
  rtcninja:RTCPeerConnection onsignalingstatechange() | signalingState: stable +0ms
  rtcninja:RTCPeerConnection onicegatheringstatechange() | iceGatheringState: new +0ms
  rtcninja:RTCPeerConnection oniceconnectionstatechange() | iceConnectionState: new +0ms
  rtcninja:RTCPeerConnection createOffer() | success +1ms
  rtcninja:RTCPeerConnection setLocalDescription() +0ms
  rtcninja:FakePlugin:RTCPeerConnection setLocalDescription() +0ms
  rtcninja:RTCPeerConnection onicegatheringstatechange() | iceGatheringState: gathering +0ms
  rtcninja:RTCPeerConnection setLocalDescription() | success +1ms
  rtcninja:RTCPeerConnection onicegatheringstatechange() | iceGatheringState: complete +2ms
  rtcninja:RTCPeerConnection onicecandidate() | end of candidates +0ms
  rtcninja:RTCPeerConnection onsignalingstatechange() | signalingState: have-local-offer +1ms
  rtcninja:RTCPeerConnection setRemoteDescription() +37ms
  rtcninja:FakePlugin:RTCPeerConnection setRemoteDescription() +0ms
  rtcninja:RTCPeerConnection setRemoteDescription() | success +2ms
call confirmed
ConnectionStateChanged to CONNECTED
Kurento is recording
Answer to Kurento sent
  rtcninja:RTCPeerConnection onsignalingstatechange() | signalingState: stable +12ms
Kurento is playing
  rtcninja:RTCPeerConnection oniceconnectionstatechange() | iceConnectionState: checking +0ms
  rtcninja:RTCPeerConnection oniceconnectionstatechange() | iceConnectionState: connected +1ms
  rtcninja:RTCPeerConnection oniceconnectionstatechange() | iceConnectionState: completed +0ms
  rtcninja:RTCPeerConnection close() +1s
  rtcninja:FakePlugin:RTCPeerConnection close() +0ms
Call ended: Terminated
```

**Comment by ibc** [comment]
``` js
+Utils.try_nomedia = function(rtcninja) {
+  if (!(typeof module !== 'undefined' && module.exports))
+    return;
+  try {
+    var rtcninjaFake = require('rtcninja-fake');
+    rtcninja({plugin: rtcninjaFake});
+  }
+  catch (e) {
+    if (e instanceof Error && e.code === "MODULE_NOT_FOUND")
+        console.log("Can't load rtcninja-fake");
+    else
+        throw e;
+  }
+}
```

No, that's not valid. You can call `rtcninja()` by yourself (`JsSIP.rtcninja` does exist):

``` js
var JsSIP = require('jssip');
var rtcninja = JsSIP.rtcninja;
var rtcninjaFake = require('rtcninja-fake');

// Load rtcninja with the rtcninja-fake plugin.
rtcninja({plugin: rtcninjaFake});

// Use JsSIP now
```

I won't accept `rtcninja-fake` as a JsSIP dependency, nor a helper method that loads it dynamically.

**Comment by ibc** [comment]
Also I won't accept a PR that breaks syntax rules. JsSIP does not use `console.log()` nor double quotes. Running `gulp` checks the style.

Anyhow, there is nothing to add within JsSIP to make `rtcninja-fake` work with it.

**Comment by ibc** [comment]
Said that, please send a PR to this `rtcninja-fake` project so you have published versions of all the libraries you need.

**Comment by Sfinx** [comment]
I thought we are discussing here the rtcninja-fake only. Ok, nevermind - this was my first and last try to use JsSIP. Good bye

**Comment by ibc** [comment]
> I though we are discussing here the rtcninja-fake only

Wrong, you said:

> The only problem is that it requires the _jssip_ and rtcninja-fake patches to run.

And it happens that the "jssip patch" you meant is not acceptable at all due the rationale given above.

> this was my first and last try to use JsSIP

Really good bye.
